export default {
  home: {
    tagline: 'Discover how you learn best',
    chip1: 'Validated tests', chip2: 'Detailed analysis', chip3: 'Continuous improvement',
    heroTitle: 'How do you learn?',
    heroDesc: 'Every person has a unique learning profile. Our tests based on recognized scientific models help you discover yours.',
    sectionTitle: 'Choose your test',
    basicCard: { title: 'Basic VARK Test', subtitle: 'Identify your primary learning style among the 4 VARK styles', tag: 'FREE', duration: '5–8 min' },
    premiumCard: { title: 'Advanced Premium Test', subtitle: "Complete profile of Howard Gardner's 8 Multiple Intelligences", tag: 'PREMIUM', duration: '12–18 min' },
    startBtn: 'Start Test →',
    questions: (n) => `${n} questions`,
    aboutTitle: 'What does each test measure?',
    aboutBasicLabel: 'Basic Test — VARK',
    aboutBasicText: 'The VARK model (Visual, Auditory, Reading/Writing, Kinesthetic) identifies how you prefer to receive and process new information.',
    aboutPremiumLabel: 'Premium Test — Multiple Intelligences',
    aboutPremiumText: "Howard Gardner's theory (1983) proposes 8 types of intelligence. This test creates your complete profile with career recommendations and personalized strategies.",
    disclaimerBtn: 'View important legal disclaimer',
  },
  basicIntro: {
    back: '← Home',
    statsQuestions: 'Questions', statsDuration: 'Duration', statsStyles: 'Styles',
    descTitle: 'What does this test measure?',
    sectionTitle: 'The 4 VARK styles',
    vLabel: 'Visual', aLabel: 'Auditory', rLabel: 'Reading/Writing', kLabel: 'Kinesthetic',
    instructTitle: '📋 How to answer',
    instructText1: 'For each question, choose the option that best describes your usual behavior. There are no right or wrong answers — be honest with yourself.',
    instructText2: 'The test includes a results visualization with your percentage in each style and personalized recommendations.',
    disclaimerText: 'Results are indicative and not conclusive for legal, medical or formal educational purposes.',
    disclaimerLink: 'View full disclaimer',
    cta: '🚀 Start Basic Test',
  },
  basicTest: {
    back: '‹ Back',
    catBadge: 'Learning preferences',
    questionLabel: (n) => `Question ${n}`,
    chooseText: 'Select the option that best describes you:',
    remaining: (n) => `${n} questions remaining`,
  },
  basicResult: {
    completed: '✅ Test completed',
    resultLabel: 'Your primary style',
    whatMeans: 'What does this mean?',
    profile: '📊 Your learning profile',
    strengths: '💪 Your strengths',
    strategies: '🎯 Learning strategies',
    disclaimerText: 'These results are ',
    disclaimerBold: 'approximate and indicative',
    disclaimerText2: '. They are not conclusive for legal, medical or formal educational purposes. For a professional evaluation, consult a qualified specialist.',
    disclaimerLink: 'View full legal disclaimer →',
    premiumTitle: 'Discover more with the Premium Test',
    premiumSub: '8 Multiple Intelligences • Career recommendations',
    backHome: '← Back to home',
  },
  premiumIntro: {
    back: '← Home',
    statsQuestions: 'Questions', statsIntelligences: 'Intelligences', statsDuration: 'Duration',
    includesTitle: '✨ This test includes',
    sectionTitle: "Gardner's 8 Intelligences",
    scaleTitle: '📏 Response scale',
    scaleDesc: 'For each statement, indicate how much you agree from 1 to 5:',
    scaleLabels: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    disclaimerText: 'Results are indicative and not conclusive for legal, clinical or formal educational purposes.',
    disclaimerLink: 'View full legal disclaimer →',
    cta: '⭐ Start Premium Test',
  },
  disclaimer: {
    back: '← Back',
    headerTitle: 'Legal Disclaimer',
    headerSubtitle: 'Important information about results',
    mainTitle: 'IMPORTANT STATEMENT',
    mainText1: 'The results of the tests contained in this application are ',
    mainBold: 'approximate, indicative and NOT conclusive',
    mainText2: '. Under no circumstances should they be used as the sole or definitive criterion for decisions of a medical, clinical, official educational, labor, psychological, legal or any other binding nature.',
    s1Title: '📋 Nature of results',
    s1p1: 'The tests are based on widely recognized theoretical models in educational psychology (VARK, Gardner\'s Multiple Intelligences), but they are self-reflection tools, NOT clinical diagnoses.',
    s1p2: 'The results are an approximate snapshot of learning tendencies and preferences at the time of evaluation and may vary over time.',
    s1p3: 'These tests have an orientative and self-knowledge purpose. They do NOT replace the evaluation of a qualified professional (psychologist, pedagogue, neuropsychologist).',
    s2Title: '🚫 Limitations and prohibited uses',
    s2p1: 'Results should NOT be used as a basis for diagnosing learning disorders (dyslexia, ADHD, ASD or others).',
    s2p2: 'They should not be used in legal, judicial, medical, personnel selection or official academic evaluation processes.',
    s2p3: "Results do NOT define a person's absolute intellectual capacities, nor determine their success or failure in any area.",
    s2p4: 'This application does NOT provide medical, psychological, psychiatric or therapeutic advice of any kind.',
    s3Title: '✅ Recommended uses',
    s3p1: 'Personal reflection on learning preferences and habits.',
    s3p2: 'Initial guidance for exploring more effective study strategies.',
    s3p3: 'Starting point for conversations with educators or academic tutors.',
    s3p4: 'Self-knowledge tool for personal development purposes.',
    s4Title: '📱 About the application',
    s4Text: 'LearnIQ is an educational guidance application for informational and personal development purposes. The development team has designed the tests rigorously and following recognized theoretical frameworks, but cannot guarantee the absolute accuracy of the results, as these depend on multiple individual, cultural and contextual factors beyond the scope of any self-report test.',
    s5Title: '🔒 Data privacy',
    s5p1: 'Test results are stored only on your device and are NOT transmitted to external servers.',
    s5p2: 'The application does not collect personally identifiable data without your explicit consent.',
    s5p3: 'You can delete your results history at any time from the app settings.',
    s6Title: '⚖️ Disclaimer of liability',
    s6Text: 'The developers and distributors of LearnIQ are exempt from any liability arising from the use or incorrect interpretation of the results generated by the tests. Use of this application implies full acceptance of the terms set out here.\n\nIf you experience significant learning, emotional or cognitive difficulties, we recommend consulting a duly qualified mental health or educational professional.',
    footer1: 'Version 1.0.0 • LearnIQ © 2025',
    footer2: 'Based on the VARK model (Neil Fleming) and Multiple Intelligences (Howard Gardner)',
    acceptBtn: 'Understood — Back to home',
  },
  payment: {
    premiumBadge: '⭐ PREMIUM',
    productTitle: 'Advanced Multiple\nIntelligences Test',
    productSub: 'Based on Howard Gardner\'s theory · 40 questions',
    priceNote: 'One-time payment · No subscriptions',
    features: [
      { icon: '🧠', text: '40 questions to help you understand how you learn' },
      { icon: '📊', text: 'Detailed profile of all 8 intelligences' },
      { icon: '🎯', text: 'Personalized career recommendations' },
      { icon: '📚', text: 'Exclusive learning strategies' },
      { icon: '🔒', text: 'Lifetime access · One-time payment' },
    ],
    loading: 'Connecting to PayPal...',
    payBtnText: '  ·  Pay €4.99',
    security: 'Payment 100% secure managed by PayPal. We do not store payment data.',
    webviewTitle: 'Secure payment with PayPal',
    webviewBack: '← Back',
    webviewLoading: 'Loading PayPal...',
    successTitle: 'Payment completed!',
    successSub: 'Welcome to the Premium\nMultiple Intelligences Test',
    successCard: '🏆 Premium access activated',
    successBtn: 'Start Premium Test →',
    errorTitle: 'Connection error',
    errorMsg: 'Could not connect to the payment server.\nMake sure the backend is running.',
    errorCaptureTitle: 'Payment not completed',
    errorCaptureMsg: 'There was a problem processing the payment. Please try again.',
    backBtn: '← Back',
  },
  data: {
    basicTestIntro: {
      title: 'Basic VARK Test',
      subtitle: 'Discover your primary learning style',
      description: 'This 6-question test will identify whether you are a Visual, Auditory, Reading/Writing, or Kinesthetic (VARK) learner.',
      duration: '2–3 min',
      questions: 6,
    },
    basicQuestions: [
      { id: 1, text: 'When learning something new, you prefer to…', options: [{ id: 'a', text: 'Look at diagrams, maps or charts', category: 'V' }, { id: 'b', text: 'Listen to someone explain it to you', category: 'A' }, { id: 'c', text: 'Read a detailed book or manual', category: 'R' }, { id: 'd', text: 'Practice it directly with your hands', category: 'K' }] },
      { id: 2, text: 'When studying for an exam, you find it most helpful to…', options: [{ id: 'a', text: 'Create outlines and mind maps', category: 'V' }, { id: 'b', text: 'Repeat the material out loud', category: 'A' }, { id: 'c', text: 'Read and re-read your notes', category: 'R' }, { id: 'd', text: 'Do practical exercises and real-life cases', category: 'K' }] },
      { id: 3, text: 'When solving a new problem, you tend to…', options: [{ id: 'a', text: 'Draw it or make a diagram', category: 'V' }, { id: 'b', text: 'Talk it through with someone', category: 'A' }, { id: 'c', text: 'Look for written information', category: 'R' }, { id: 'd', text: 'Try different solutions until one works', category: 'K' }] },
      { id: 4, text: 'In your free time, you most enjoy…', options: [{ id: 'a', text: 'Watching movies, photography or visual art', category: 'V' }, { id: 'b', text: 'Listening to podcasts, music or conversations', category: 'A' }, { id: 'c', text: 'Reading books, articles or news', category: 'R' }, { id: 'd', text: 'Playing sports or hands-on activities', category: 'K' }] },
      { id: 5, text: 'When something is unclear to you, you ask…', options: [{ id: 'a', text: '"Can you show me an example or image?"', category: 'V' }, { id: 'b', text: '"Can you explain it to me again?"', category: 'A' }, { id: 'c', text: '"Do you have something written about this?"', category: 'R' }, { id: 'd', text: '"Can I try it myself?"', category: 'K' }] },
      { id: 6, text: 'To memorize information, what works best for you is…', options: [{ id: 'a', text: 'Associating it with colors or mental images', category: 'V' }, { id: 'b', text: 'Repeating it out loud several times', category: 'A' }, { id: 'c', text: 'Writing it down multiple times', category: 'R' }, { id: 'd', text: 'Associating it with a movement or action', category: 'K' }] },
    ],
    basicResults: {
      V: { label: 'Visual', emoji: '👁️', color: '#7C3AED', gradient: ['#7C3AED', '#5B21B6'], title: 'Visual Learner', description: 'You process information best through images, graphics, colors and spatial representations. Your brain converts abstract concepts into vivid mental images.', strengths: ['Excellent photographic memory', 'Think in images and colors', 'Organize information spatially', 'Appreciate design and visual order'], tips: ['Use mind maps and diagrams', 'Highlight with colors when studying', 'Convert texts into visual outlines', 'Keep your study space free from visual distractions'] },
      A: { label: 'Auditory', emoji: '🎧', color: '#3B82F6', gradient: ['#3B82F6', '#1D4ED8'], title: 'Auditory Learner', description: 'You learn best by listening, speaking, and participating in discussions. Sound and rhythm are your natural allies for retaining and understanding information.', strengths: ['Excellent at following verbal explanations', 'Good memory for conversations', 'Learns languages easily', 'Thrives in debates and discussions'], tips: ['Listen to podcasts and audiobooks', 'Repeat what you study out loud', 'Form study groups to discuss topics', 'Use background music while studying'] },
      R: { label: 'Reading/Writing', emoji: '📚', color: '#10B981', gradient: ['#10B981', '#059669'], title: 'Reading/Writing Learner', description: 'Your learning thrives through written text. You are an avid reader and writer who prefers information presented in words, whether reading or writing.', strengths: ['Excellent reading comprehension', 'Enjoys researching and reading extensively', 'Very organized with notes', 'Writes with clarity and precision'], tips: ['Always take detailed notes', 'Rewrite material in your own words', 'Read multiple sources on each topic', 'Create structured summaries and lists'] },
      K: { label: 'Kinesthetic', emoji: '🤲', color: '#F59E0B', gradient: ['#F59E0B', '#D97706'], title: 'Kinesthetic Learner', description: 'You learn by doing. You need to experience, touch and practice for information to consolidate in your memory. Hands-on projects and movement are key for you.', strengths: ['Learns quickly by doing things', 'Excellent coordination and practical skills', 'Good at real-world problem-solving', 'Remembers physical experiences well'], tips: ['Always seek hands-on experiences', 'Build real projects with what you learn', 'Take active breaks while studying', 'Connect concepts to real-world examples'] },
    },
    premiumTestIntro: {
      title: 'Advanced Premium Test',
      subtitle: 'Complete intelligence and cognitive style profile',
      description: 'A deep 40-question analysis that evaluates your 8 Multiple Intelligences (Gardner), your cognitive style and personalized career and learning recommendations.',
      duration: '12–18 min',
      questions: 40,
      includes: ["Gardner's 8 Multiple Intelligences", 'Cognitive style profile', 'Strengths and areas for improvement analysis', 'Related career recommendations', 'Personalized learning plan', 'Detailed exportable report'],
    },
    premiumQuestions: [
      { id: 1, section: 'Multiple Intelligences', text: 'I enjoy playing with words, creating poems or telling stories.', category: 'LG', scale: true },
      { id: 2, section: 'Multiple Intelligences', text: 'I find it easy to explain complex concepts clearly and simply.', category: 'LG', scale: true },
      { id: 3, section: 'Multiple Intelligences', text: 'I regularly read for pleasure and enjoy literature.', category: 'LG', scale: true },
      { id: 4, section: 'Multiple Intelligences', text: 'I enjoy debating and convincing others with solid arguments.', category: 'LG', scale: true },
      { id: 5, section: 'Multiple Intelligences', text: 'I learn new languages with relative ease.', category: 'LG', scale: true },
      { id: 6, section: 'Multiple Intelligences', text: 'I enjoy solving puzzles, riddles and math problems.', category: 'LM', scale: true },
      { id: 7, section: 'Multiple Intelligences', text: 'I look for patterns and logical relationships in any situation.', category: 'LM', scale: true },
      { id: 8, section: 'Multiple Intelligences', text: 'I tend to think in a structured, step-by-step manner.', category: 'LM', scale: true },
      { id: 9, section: 'Multiple Intelligences', text: 'I am interested in science, programming or mathematics.', category: 'LM', scale: true },
      { id: 10, section: 'Multiple Intelligences', text: 'I enjoy classifying, categorizing and analyzing data.', category: 'LM', scale: true },
      { id: 11, section: 'Multiple Intelligences', text: 'I have good spatial orientation and rarely get lost.', category: 'ES', scale: true },
      { id: 12, section: 'Multiple Intelligences', text: 'I enjoy designing, drawing or creating visual things.', category: 'ES', scale: true },
      { id: 13, section: 'Multiple Intelligences', text: 'I can clearly imagine how something will look before creating it.', category: 'ES', scale: true },
      { id: 14, section: 'Multiple Intelligences', text: 'I find it easy to read maps, blueprints and 3D graphs.', category: 'ES', scale: true },
      { id: 15, section: 'Multiple Intelligences', text: 'I notice visual details that others tend to miss.', category: 'ES', scale: true },
      { id: 16, section: 'Multiple Intelligences', text: 'I easily identify the rhythm, melody or pitch of a song.', category: 'MI', scale: true },
      { id: 17, section: 'Multiple Intelligences', text: 'I play an instrument or would like to learn one.', category: 'MI', scale: true },
      { id: 18, section: 'Multiple Intelligences', text: 'Music significantly influences my emotional state.', category: 'MI', scale: true },
      { id: 19, section: 'Multiple Intelligences', text: 'I remember songs easily and notice when there are musical mistakes.', category: 'MI', scale: true },
      { id: 20, section: 'Multiple Intelligences', text: 'Studying with music helps me concentrate better.', category: 'MI', scale: true },
      { id: 21, section: 'Multiple Intelligences', text: 'I learn better by doing things with my hands.', category: 'KC', scale: true },
      { id: 22, section: 'Multiple Intelligences', text: 'I am skilled at sports, dance or other physical activities.', category: 'KC', scale: true },
      { id: 23, section: 'Multiple Intelligences', text: 'I find it difficult to stay still for a long time.', category: 'KC', scale: true },
      { id: 24, section: 'Multiple Intelligences', text: 'I have good hand-eye coordination and physical precision.', category: 'KC', scale: true },
      { id: 25, section: 'Multiple Intelligences', text: 'I gesture a lot and use my body to express myself.', category: 'KC', scale: true },
      { id: 26, section: 'Multiple Intelligences', text: 'I know myself well: my strengths, weaknesses and emotions.', category: 'IN', scale: true },
      { id: 27, section: 'Multiple Intelligences', text: 'I prefer to work alone and at my own pace.', category: 'IN', scale: true },
      { id: 28, section: 'Multiple Intelligences', text: 'I reflect deeply before making important decisions.', category: 'IN', scale: true },
      { id: 29, section: 'Multiple Intelligences', text: 'I have clear values, goals and life purpose.', category: 'IN', scale: true },
      { id: 30, section: 'Multiple Intelligences', text: 'I enjoy creative solitude and moments of introspection.', category: 'IN', scale: true },
      { id: 31, section: 'Multiple Intelligences', text: 'I easily understand how others are feeling.', category: 'IE', scale: true },
      { id: 32, section: 'Multiple Intelligences', text: 'I am good at resolving conflicts and mediating between people.', category: 'IE', scale: true },
      { id: 33, section: 'Multiple Intelligences', text: 'I prefer to learn and work in groups.', category: 'IE', scale: true },
      { id: 34, section: 'Multiple Intelligences', text: 'People often come to me for advice.', category: 'IE', scale: true },
      { id: 35, section: 'Multiple Intelligences', text: 'I adapt well to different types of people and social situations.', category: 'IE', scale: true },
      { id: 36, section: 'Multiple Intelligences', text: 'I enjoy being in nature and observing the natural world.', category: 'NT', scale: true },
      { id: 37, section: 'Multiple Intelligences', text: 'I am interested in biology, ecology or the environment.', category: 'NT', scale: true },
      { id: 38, section: 'Multiple Intelligences', text: 'I am good at classifying and distinguishing animal or plant species.', category: 'NT', scale: true },
      { id: 39, section: 'Multiple Intelligences', text: 'I care about the environment and planetary sustainability.', category: 'NT', scale: true },
      { id: 40, section: 'Multiple Intelligences', text: 'I notice patterns in nature that others do not easily see.', category: 'NT', scale: true },
    ],
    scaleOptions: [
      { id: 1, label: 'Strongly disagree', short: '1', value: 1 },
      { id: 2, label: 'Disagree', short: '2', value: 2 },
      { id: 3, label: 'Neutral', short: '3', value: 3 },
      { id: 4, label: 'Agree', short: '4', value: 4 },
      { id: 5, label: 'Strongly agree', short: '5', value: 5 },
    ],
    premiumIntelligences: {
      LG: { label: 'Linguistic', emoji: '📝', color: '#7C3AED', gradient: ['#7C3AED', '#5B21B6'], description: 'Ability to use language with precision, both orally and in writing.', careers: ['Writer', 'Journalist', 'Lawyer', 'Language Teacher', 'Translator', 'Broadcaster'], famous: 'Shakespeare, Gabriel García Márquez, Obama', studyTips: ['Write summaries of what you learned', 'Create stories using key concepts', 'Debate and discuss topics out loud'] },
      LM: { label: 'Logical-Mathematical', emoji: '🔢', color: '#3B82F6', gradient: ['#3B82F6', '#1D4ED8'], description: 'Ability to reason deductively, solve mathematical problems and think scientifically.', careers: ['Engineer', 'Scientist', 'Programmer', 'Accountant', 'Data Analyst', 'Physicist'], famous: 'Einstein, Hawking, Ada Lovelace', studyTips: ['Use tables and logical diagrams', 'Apply real-world problems to concepts', 'Learn through experimentation'] },
      ES: { label: 'Spatial', emoji: '🎨', color: '#EC4899', gradient: ['#EC4899', '#BE185D'], description: 'Ability to perceive the visual-spatial world accurately and transform initial perceptions.', careers: ['Architect', 'Graphic Designer', 'Pilot', 'Sculptor', 'Surgeon', 'Photographer'], famous: 'Da Vinci, Picasso, Frank Lloyd Wright', studyTips: ['Use color-coded mind maps', 'Visualize concepts as images', 'Learn with diagrams and 3D models'] },
      MI: { label: 'Musical', emoji: '🎵', color: '#F59E0B', gradient: ['#F59E0B', '#D97706'], description: 'Sensitivity to rhythm, melody, timbre and harmony.', careers: ['Musician', 'Composer', 'Orchestra Conductor', 'Music Producer', 'Music Therapist'], famous: 'Mozart, Beethoven, Björk, Miles Davis', studyTips: ['Turn concept lists into songs', 'Study with instrumental background music', 'Use rhythms to memorize sequences'] },
      KC: { label: 'Bodily-Kinesthetic', emoji: '⚡', color: '#10B981', gradient: ['#10B981', '#059669'], description: 'Ability to use the body to express oneself or to solve problems. Precise motor control.', careers: ['Athlete', 'Dancer', 'Surgeon', 'Actor/Actress', 'Physical Therapist', 'Craftsperson'], famous: 'Michael Jordan, Simone Biles, Charlie Chaplin', studyTips: ['Learn while walking or moving', 'Use physical objects to represent concepts', 'Practice hands-on before theorizing'] },
      IN: { label: 'Intrapersonal', emoji: '🧘', color: '#8B5CF6', gradient: ['#8B5CF6', '#6D28D9'], description: "Ability to know oneself deeply, manage one's own emotions, motivations and goals.", careers: ['Psychologist', 'Philosopher', 'Writer', 'Researcher', 'Entrepreneur', 'Life Coach'], famous: 'Sigmund Freud, Frida Kahlo, Nietzsche', studyTips: ['Keep a reflective learning journal', 'Study in solitude at your own pace', 'Connect every concept to your personal experience'] },
      IE: { label: 'Interpersonal', emoji: '🤝', color: '#EF4444', gradient: ['#EF4444', '#DC2626'], description: 'Ability to understand the intentions, motivations and desires of others.', careers: ['Leader', 'Teacher', 'Politician', 'Therapist', 'Social Worker', 'Salesperson'], famous: 'Nelson Mandela, Oprah Winfrey, Gandhi', studyTips: ['Learn in study groups', 'Teach what you learned to others', 'Participate in debates and forums'] },
      NT: { label: 'Naturalistic', emoji: '🌿', color: '#84CC16', gradient: ['#84CC16', '#65A30D'], description: 'Ability to recognize and categorize natural objects and patterns.', careers: ['Biologist', 'Ecologist', 'Veterinarian', 'Geographer', 'Chef', 'Landscape Designer'], famous: 'Charles Darwin, Jane Goodall, David Attenborough', studyTips: ['Learn in contact with nature', 'Classify and categorize information like a taxonomy', 'Relate concepts to natural phenomena'] },
    },
  },
};
