export default {
  home: {
    tagline: 'Descubre cómo aprendes mejor',
    chip1: 'Tests validados', chip2: 'Análisis detallado', chip3: 'Mejora continua',
    heroTitle: '¿Cómo aprendes?',
    heroDesc: 'Cada persona tiene un perfil de aprendizaje único. Nuestros tests basados en modelos científicos reconocidos te ayudan a descubrirlo.',
    sectionTitle: 'Elige tu test',
    basicCard: { title: 'Test VARK Básico', subtitle: 'Identifica tu estilo principal de aprendizaje entre los 4 estilos VARK', tag: 'GRATUITO', duration: '5–8 min' },
    premiumCard: { title: 'Test Premium Avanzado', subtitle: 'Perfil completo de las 8 Inteligencias Múltiples de Howard Gardner', tag: 'PREMIUM', duration: '12–18 min' },
    startBtn: 'Comenzar Test →',
    questions: (n) => `${n} preguntas`,
    aboutTitle: '¿Qué evalúa cada test?',
    aboutBasicLabel: 'Test Básico — VARK',
    aboutBasicText: 'El modelo VARK (Visual, Auditivo, Lecto-escritor, Kinestésico) identifica cómo prefieres recibir y procesar información nueva.',
    aboutPremiumLabel: 'Test Premium — Inteligencias Múltiples',
    aboutPremiumText: 'La teoría de Howard Gardner (1983) propone 8 tipos de inteligencia. Este test crea tu perfil completo con recomendaciones de carrera y estrategias personalizadas.',
    disclaimerBtn: 'Ver aviso legal importante',
  },
  basicIntro: {
    back: '← Inicio',
    statsQuestions: 'Preguntas', statsDuration: 'Duración', statsStyles: 'Estilos',
    descTitle: '¿Qué mide este test?',
    sectionTitle: 'Los 4 estilos VARK',
    vLabel: 'Visual', aLabel: 'Auditivo', rLabel: 'Lecto-escritor', kLabel: 'Kinestésico',
    instructTitle: '📋 Cómo responder',
    instructText1: 'Para cada pregunta, elige la opción que mejor describe tu comportamiento habitual. No hay respuestas correctas o incorrectas — sé honesto/a contigo mismo/a.',
    instructText2: 'El test incluye la visualización de resultados con tu porcentaje en cada estilo y recomendaciones personalizadas.',
    disclaimerText: 'Los resultados son orientativos y no concluyentes para fines legales, médicos o educativos formales.',
    disclaimerLink: 'Ver aviso completo',
    cta: '🚀 Comenzar Test Básico',
  },
  basicTest: {
    back: '‹ Atrás',
    catBadge: 'Preferencias de aprendizaje',
    questionLabel: (n) => `Pregunta ${n}`,
    chooseText: 'Selecciona la opción que mejor te describe:',
    remaining: (n) => `${n} preguntas restantes`,
  },
  basicResult: {
    completed: '✅ Test completado',
    resultLabel: 'Tu estilo principal',
    whatMeans: '¿Qué significa esto?',
    profile: '📊 Tu perfil de aprendizaje',
    strengths: '💪 Tus fortalezas',
    strategies: '🎯 Estrategias de aprendizaje',
    disclaimerText: 'Estos resultados son ',
    disclaimerBold: 'aproximados y orientativos',
    disclaimerText2: '. No son concluyentes para fines legales, médicos o educativos formales. Para una evaluación profesional, consulta con un especialista cualificado.',
    disclaimerLink: 'Ver aviso legal completo →',
    premiumTitle: 'Descubre más con el Test Premium',
    premiumSub: '8 Inteligencias Múltiples • Recomendaciones de carrera',
    backHome: '← Volver al inicio',
  },
  premiumIntro: {
    back: '← Inicio',
    statsQuestions: 'Preguntas', statsIntelligences: 'Inteligencias', statsDuration: 'Duración',
    includesTitle: '✨ Este test incluye',
    sectionTitle: 'Las 8 Inteligencias de Gardner',
    scaleTitle: '📏 Escala de respuestas',
    scaleDesc: 'Para cada afirmación, indica qué tan de acuerdo estás del 1 al 5:',
    scaleLabels: ['Muy en desacuerdo', 'En desacuerdo', 'Neutral', 'De acuerdo', 'Muy de acuerdo'],
    disclaimerText: 'Los resultados son orientativos y no concluyentes para fines legales, clínicos o educativos formales.',
    disclaimerLink: 'Ver aviso legal completo →',
    cta: '⭐ Comenzar Test Premium',
  },
  disclaimer: {
    back: '← Volver',
    headerTitle: 'Aviso Legal',
    headerSubtitle: 'Información importante sobre los resultados',
    mainTitle: 'DECLARACIÓN IMPORTANTE',
    mainText1: 'Los resultados de los tests contenidos en esta aplicación son ',
    mainBold: 'aproximados, orientativos y NO concluyentes',
    mainText2: '. Bajo ninguna circunstancia deben utilizarse como criterio único o definitivo para decisiones de carácter médico, clínico, educativo oficial, laboral, psicológico, legal o de cualquier otra naturaleza vinculante.',
    s1Title: '📋 Naturaleza de los resultados',
    s1p1: 'Los tests están basados en modelos teóricos ampliamente reconocidos en psicología educativa (VARK, Inteligencias Múltiples de Gardner), pero son herramientas de auto-reflexión, NO diagnósticos clínicos.',
    s1p2: 'Los resultados son una fotografía aproximada de las tendencias y preferencias de aprendizaje en el momento de la evaluación y pueden variar con el tiempo.',
    s1p3: 'Estos tests tienen un propósito orientativo y de autoconocimiento. NO sustituyen la evaluación de un profesional cualificado (psicólogo, pedagogo, neuropsicólogo).',
    s2Title: '🚫 Limitaciones y usos no permitidos',
    s2p1: 'Los resultados NO deben usarse como base para diagnósticos de trastornos del aprendizaje (dislexia, TDAH, TEA u otros).',
    s2p2: 'No deben utilizarse en procesos legales, judiciales, médicos, de selección de personal o evaluaciones académicas oficiales.',
    s2p3: 'Los resultados NO definen las capacidades intelectuales absolutas de una persona, ni determinan su éxito o fracaso en cualquier ámbito.',
    s2p4: 'Esta aplicación NO proporciona consejo médico, psicológico, psiquiátrico ni terapéutico de ningún tipo.',
    s3Title: '✅ Usos recomendados',
    s3p1: 'Reflexión personal sobre preferencias y hábitos de aprendizaje.',
    s3p2: 'Orientación inicial para explorar estrategias de estudio más eficaces.',
    s3p3: 'Punto de partida para conversaciones con educadores o tutores académicos.',
    s3p4: 'Herramienta de autoconocimiento con fines de desarrollo personal.',
    s4Title: '📱 Sobre la aplicación',
    s4Text: 'LearnIQ es una aplicación de orientación educativa con fines informativos y de desarrollo personal. El equipo de desarrollo ha diseñado los tests con rigor y siguiendo marcos teóricos reconocidos, pero no puede garantizar la exactitud absoluta de los resultados, ya que estos dependen de múltiples factores individuales, culturales y contextuales que escapan al alcance de cualquier test de auto-reporte.',
    s5Title: '🔒 Privacidad de datos',
    s5p1: 'Los resultados de los tests se almacenan únicamente en tu dispositivo y NO se transmiten a servidores externos.',
    s5p2: 'La aplicación no recopila datos personales identificables sin tu consentimiento explícito.',
    s5p3: 'Puedes borrar tu historial de resultados en cualquier momento desde la configuración de la app.',
    s6Title: '⚖️ Exoneración de responsabilidad',
    s6Text: 'Los desarrolladores y distribuidores de LearnIQ quedan exonerados de toda responsabilidad derivada del uso o interpretación incorrecta de los resultados generados por los tests. El uso de esta aplicación implica la aceptación plena de los términos aquí expuestos.\n\nSi experimentas dificultades significativas de aprendizaje, emocionales o cognitivas, te recomendamos consultar con un profesional de la salud mental o educativa debidamente cualificado.',
    footer1: 'Versión 1.0.0 • LearnIQ © 2025',
    footer2: 'Basado en el modelo VARK (Neil Fleming) y las Inteligencias Múltiples (Howard Gardner)',
    acceptBtn: 'Entendido — Volver al inicio',
  },
  payment: {
    premiumBadge: '⭐ PREMIUM',
    productTitle: 'Test de Inteligencias\nMúltiples Avanzado',
    productSub: 'Basado en la teoría de Howard Gardner · 40 preguntas',
    priceNote: 'Pago único · Sin suscripciones',
    features: [
      { icon: '🧠', text: '40 preguntas científicamente validadas' },
      { icon: '📊', text: 'Perfil detallado de las 8 inteligencias' },
      { icon: '🎯', text: 'Recomendaciones de carrera personalizadas' },
      { icon: '📚', text: 'Estrategias de aprendizaje exclusivas' },
      { icon: '🔒', text: 'Acceso de por vida · Pago único' },
    ],
    loading: 'Conectando con PayPal...',
    payBtnText: '  ·  Pagar €4.99',
    security: 'Pago 100% seguro gestionado por PayPal. No almacenamos datos de pago.',
    webviewTitle: 'Pago seguro con PayPal',
    webviewBack: '← Volver',
    webviewLoading: 'Cargando PayPal...',
    successTitle: '¡Pago completado!',
    successSub: 'Bienvenido al Test Premium de\nInteligencias Múltiples',
    successCard: '🏆 Acceso Premium activado',
    successBtn: 'Comenzar el Test Premium →',
    errorTitle: 'Error de conexión',
    errorMsg: 'No se pudo conectar con el servidor de pagos.\nAsegúrate de que el backend está corriendo.',
    errorCaptureTitle: 'Pago no completado',
    errorCaptureMsg: 'Hubo un problema al procesar el pago. Por favor inténtalo de nuevo.',
    backBtn: '← Volver',
  },
  data: {
    basicTestIntro: {
      title: 'Test Básico VARK',
      subtitle: 'Descubre tu estilo de aprendizaje principal',
      description: 'Este test de 6 preguntas identificará si eres un aprendiz Visual, Auditivo, Lecto-escritor o Kinestésico (VARK).',
      duration: '2–3 min',
      questions: 6,
    },
    basicQuestions: [
      { id: 1, text: 'Cuando aprendes algo nuevo, prefieres…', options: [{ id: 'a', text: 'Ver diagramas, mapas o gráficos', category: 'V' }, { id: 'b', text: 'Escuchar a alguien explicártelo', category: 'A' }, { id: 'c', text: 'Leer un libro o manual detallado', category: 'R' }, { id: 'd', text: 'Practicarlo directamente con tus manos', category: 'K' }] },
      { id: 2, text: 'Cuando estudias para un examen, te resulta más útil…', options: [{ id: 'a', text: 'Crear esquemas y mapas conceptuales', category: 'V' }, { id: 'b', text: 'Repetir en voz alta el material', category: 'A' }, { id: 'c', text: 'Leer y releer tus apuntes', category: 'R' }, { id: 'd', text: 'Hacer ejercicios prácticos y casos reales', category: 'K' }] },
      { id: 3, text: 'Al resolver un problema nuevo, tiendes a…', options: [{ id: 'a', text: 'Dibujarlo o hacer un esquema', category: 'V' }, { id: 'b', text: 'Discutirlo con alguien', category: 'A' }, { id: 'c', text: 'Buscar información escrita', category: 'R' }, { id: 'd', text: 'Intentar diferentes soluciones hasta encontrar una', category: 'K' }] },
      { id: 4, text: 'En tu tiempo libre, sueles disfrutar más de…', options: [{ id: 'a', text: 'Ver películas, fotografía o arte visual', category: 'V' }, { id: 'b', text: 'Escuchar podcasts, música o conversaciones', category: 'A' }, { id: 'c', text: 'Leer libros, artículos o noticias', category: 'R' }, { id: 'd', text: 'Practicar deportes o actividades manuales', category: 'K' }] },
      { id: 5, text: 'Cuando algo no te queda claro, preguntas…', options: [{ id: 'a', text: '"¿Me puedes mostrar un ejemplo o imagen?"', category: 'V' }, { id: 'b', text: '"¿Me lo puedes explicar de nuevo?"', category: 'A' }, { id: 'c', text: '"¿Tienes algo escrito sobre esto?"', category: 'R' }, { id: 'd', text: '"¿Puedo intentarlo yo mismo?"', category: 'K' }] },
      { id: 6, text: 'Al memorizar información, te funciona mejor…', options: [{ id: 'a', text: 'Asociarla con colores o imágenes mentales', category: 'V' }, { id: 'b', text: 'Repetirla en voz alta varias veces', category: 'A' }, { id: 'c', text: 'Escribirla varias veces', category: 'R' }, { id: 'd', text: 'Asociarla con un movimiento o acción', category: 'K' }] },
    ],
    basicResults: {
      V: { label: 'Visual', emoji: '👁️', color: '#7C3AED', gradient: ['#7C3AED', '#5B21B6'], title: 'Aprendiz Visual', description: 'Procesas la información mejor a través de imágenes, gráficos, colores y representaciones espaciales. Tu cerebro convierte conceptos abstractos en imágenes mentales vívidas.', strengths: ['Excelente memoria fotográfica', 'Piensas en imágenes y colores', 'Organizas bien la información espacialmente', 'Aprecias el diseño y el orden visual'], tips: ['Usa mapas mentales y diagramas', 'Destaca con colores al estudiar', 'Convierte textos en esquemas visuales', 'Organiza tu espacio de estudio sin distracciones visuales'] },
      A: { label: 'Auditivo', emoji: '🎧', color: '#3B82F6', gradient: ['#3B82F6', '#1D4ED8'], title: 'Aprendiz Auditivo', description: 'Aprendes mejor escuchando, hablando y participando en discusiones. El sonido y el ritmo son tus aliados naturales para retener y comprender información.', strengths: ['Excelente para seguir explicaciones orales', 'Buena memoria para conversaciones', 'Aprende idiomas con facilidad', 'Le va bien en debates y discusiones'], tips: ['Escucha podcasts y audiolibros', 'Repite en voz alta lo que estudias', 'Forma grupos de estudio para debatir', 'Usa música de fondo mientras estudias'] },
      R: { label: 'Lecto-escritor', emoji: '📚', color: '#10B981', gradient: ['#10B981', '#059669'], title: 'Aprendiz Lecto-escritor', description: 'Tu aprendizaje florece a través del texto escrito. Eres un ávido lector y escritor que prefiere la información presentada en palabras, ya sea leyendo o escribiendo.', strengths: ['Excelente comprensión lectora', 'Disfruta investigar y leer extensamente', 'Muy organizado con sus apuntes', 'Escribe con claridad y precisión'], tips: ['Toma apuntes detallados siempre', 'Reescribe el material con tus propias palabras', 'Lee múltiples fuentes sobre cada tema', 'Crea resúmenes y listas estructuradas'] },
      K: { label: 'Kinestésico', emoji: '🤲', color: '#F59E0B', gradient: ['#F59E0B', '#D97706'], title: 'Aprendiz Kinestésico', description: 'Aprendes haciendo. Necesitas experimentar, tocar y practicar para que la información se consolide en tu memoria. Los proyectos prácticos y el movimiento son clave para ti.', strengths: ['Aprende rápido haciendo las cosas', 'Excelente coordinación y habilidades prácticas', 'Bueno en situaciones de resolución de problemas reales', 'Recuerda bien experiencias físicas'], tips: ['Busca experiencias prácticas siempre', 'Haz proyectos reales con lo que aprendes', 'Toma descansos activos mientras estudias', 'Relaciona conceptos con ejemplos del mundo real'] },
    },
    premiumTestIntro: {
      title: 'Test Premium Avanzado',
      subtitle: 'Perfil completo de inteligencias y estilos cognitivos',
      description: 'Un análisis profundo en 40 preguntas que evalúa tus 8 Inteligencias Múltiples (Gardner), tu estilo cognitivo y recomendaciones personalizadas de carrera y aprendizaje.',
      duration: '12–18 min',
      questions: 40,
      includes: ['8 Inteligencias Múltiples de Gardner', 'Perfil de estilos cognitivos', 'Análisis de fortalezas y áreas de mejora', 'Recomendaciones de carreras afines', 'Plan personalizado de aprendizaje', 'Informe detallado exportable'],
    },
    premiumQuestions: [
      { id: 1, section: 'Inteligencias Múltiples', text: 'Disfruto jugar con las palabras, crear poemas o contar historias.', category: 'LG', scale: true },
      { id: 2, section: 'Inteligencias Múltiples', text: 'Me resulta fácil explicar conceptos complejos de manera clara y sencilla.', category: 'LG', scale: true },
      { id: 3, section: 'Inteligencias Múltiples', text: 'Leo habitualmente por placer y disfruto de la literatura.', category: 'LG', scale: true },
      { id: 4, section: 'Inteligencias Múltiples', text: 'Me gusta debatir y convencer a otros con argumentos sólidos.', category: 'LG', scale: true },
      { id: 5, section: 'Inteligencias Múltiples', text: 'Aprendo idiomas nuevos con relativa facilidad.', category: 'LG', scale: true },
      { id: 6, section: 'Inteligencias Múltiples', text: 'Disfruto resolver puzzles, acertijos y problemas matemáticos.', category: 'LM', scale: true },
      { id: 7, section: 'Inteligencias Múltiples', text: 'Busco patrones y relaciones lógicas en cualquier situación.', category: 'LM', scale: true },
      { id: 8, section: 'Inteligencias Múltiples', text: 'Tiendo a pensar de manera estructurada y paso a paso.', category: 'LM', scale: true },
      { id: 9, section: 'Inteligencias Múltiples', text: 'Me interesa la ciencia, la programación o las matemáticas.', category: 'LM', scale: true },
      { id: 10, section: 'Inteligencias Múltiples', text: 'Me gusta clasificar, categorizar y analizar datos.', category: 'LM', scale: true },
      { id: 11, section: 'Inteligencias Múltiples', text: 'Tengo buena orientación espacial y rara vez me pierdo.', category: 'ES', scale: true },
      { id: 12, section: 'Inteligencias Múltiples', text: 'Disfruto diseñar, dibujar o crear cosas visuales.', category: 'ES', scale: true },
      { id: 13, section: 'Inteligencias Múltiples', text: 'Puedo imaginar con claridad cómo quedaría algo antes de crearlo.', category: 'ES', scale: true },
      { id: 14, section: 'Inteligencias Múltiples', text: 'Me resulta fácil leer mapas, planos y gráficos tridimensionales.', category: 'ES', scale: true },
      { id: 15, section: 'Inteligencias Múltiples', text: 'Noto los detalles visuales que otros pasan por alto.', category: 'ES', scale: true },
      { id: 16, section: 'Inteligencias Múltiples', text: 'Identifico fácilmente el ritmo, melodía o tono de una canción.', category: 'MI', scale: true },
      { id: 17, section: 'Inteligencias Múltiples', text: 'Toco un instrumento o me gustaría aprender uno.', category: 'MI', scale: true },
      { id: 18, section: 'Inteligencias Múltiples', text: 'La música influye significativamente en mi estado emocional.', category: 'MI', scale: true },
      { id: 19, section: 'Inteligencias Múltiples', text: 'Recuerdo las canciones con facilidad y noto cuando hay errores musicales.', category: 'MI', scale: true },
      { id: 20, section: 'Inteligencias Múltiples', text: 'Estudiar con música me ayuda a concentrarme mejor.', category: 'MI', scale: true },
      { id: 21, section: 'Inteligencias Múltiples', text: 'Aprendo mejor haciendo las cosas con mis manos.', category: 'KC', scale: true },
      { id: 22, section: 'Inteligencias Múltiples', text: 'Soy hábil en deportes, danza u otras actividades físicas.', category: 'KC', scale: true },
      { id: 23, section: 'Inteligencias Múltiples', text: 'Me resulta difícil estar quieto durante mucho tiempo.', category: 'KC', scale: true },
      { id: 24, section: 'Inteligencias Múltiples', text: 'Tengo buena coordinación mano-ojo y precisión física.', category: 'KC', scale: true },
      { id: 25, section: 'Inteligencias Múltiples', text: 'Gesticulo mucho y uso el cuerpo para expresarme.', category: 'KC', scale: true },
      { id: 26, section: 'Inteligencias Múltiples', text: 'Me conozco bien a mí mismo: mis fortalezas, debilidades y emociones.', category: 'IN', scale: true },
      { id: 27, section: 'Inteligencias Múltiples', text: 'Prefiero trabajar solo y a mi propio ritmo.', category: 'IN', scale: true },
      { id: 28, section: 'Inteligencias Múltiples', text: 'Reflexiono profundamente antes de tomar decisiones importantes.', category: 'IN', scale: true },
      { id: 29, section: 'Inteligencias Múltiples', text: 'Tengo claros mis valores, metas y propósito de vida.', category: 'IN', scale: true },
      { id: 30, section: 'Inteligencias Múltiples', text: 'Disfruto la soledad creativa y los momentos de introspección.', category: 'IN', scale: true },
      { id: 31, section: 'Inteligencias Múltiples', text: 'Entiendo fácilmente cómo se sienten los demás.', category: 'IE', scale: true },
      { id: 32, section: 'Inteligencias Múltiples', text: 'Soy bueno resolviendo conflictos y mediando entre personas.', category: 'IE', scale: true },
      { id: 33, section: 'Inteligencias Múltiples', text: 'Prefiero aprender y trabajar en grupo.', category: 'IE', scale: true },
      { id: 34, section: 'Inteligencias Múltiples', text: 'La gente suele venir a mí en busca de consejo.', category: 'IE', scale: true },
      { id: 35, section: 'Inteligencias Múltiples', text: 'Me adapto bien a diferentes tipos de personas y situaciones sociales.', category: 'IE', scale: true },
      { id: 36, section: 'Inteligencias Múltiples', text: 'Disfruto estar en la naturaleza y observar el mundo natural.', category: 'NT', scale: true },
      { id: 37, section: 'Inteligencias Múltiples', text: 'Me interesa la biología, la ecología o el medio ambiente.', category: 'NT', scale: true },
      { id: 38, section: 'Inteligencias Múltiples', text: 'Soy bueno clasificando y distinguiendo especies de animales o plantas.', category: 'NT', scale: true },
      { id: 39, section: 'Inteligencias Múltiples', text: 'Me preocupa el medio ambiente y la sostenibilidad del planeta.', category: 'NT', scale: true },
      { id: 40, section: 'Inteligencias Múltiples', text: 'Percibo patrones en la naturaleza que otros no notan fácilmente.', category: 'NT', scale: true },
    ],
    scaleOptions: [
      { id: 1, label: 'Muy en desacuerdo', short: '1', value: 1 },
      { id: 2, label: 'En desacuerdo', short: '2', value: 2 },
      { id: 3, label: 'Neutral', short: '3', value: 3 },
      { id: 4, label: 'De acuerdo', short: '4', value: 4 },
      { id: 5, label: 'Muy de acuerdo', short: '5', value: 5 },
    ],
    premiumIntelligences: {
      LG: { label: 'Lingüística', emoji: '📝', color: '#7C3AED', gradient: ['#7C3AED', '#5B21B6'], description: 'Habilidad para usar el lenguaje con precisión, tanto oral como escrito.', careers: ['Escritor/a', 'Periodista', 'Abogado/a', 'Profesor/a de idiomas', 'Traductor/a', 'Locutor/a'], famous: 'Shakespeare, García Márquez, Obama', studyTips: ['Escribe resúmenes de lo aprendido', 'Crea historias con los conceptos clave', 'Debate y discute los temas en voz alta'] },
      LM: { label: 'Lógico-Matemática', emoji: '🔢', color: '#3B82F6', gradient: ['#3B82F6', '#1D4ED8'], description: 'Capacidad para razonar de forma deductiva, resolver problemas matemáticos y pensar de manera científica.', careers: ['Ingeniero/a', 'Científico/a', 'Programador/a', 'Contador/a', 'Analista de datos', 'Físico/a'], famous: 'Einstein, Hawking, Ada Lovelace', studyTips: ['Usa tablas y esquemas lógicos', 'Aplica problemas reales a los conceptos', 'Aprende mediante la experimentación'] },
      ES: { label: 'Espacial', emoji: '🎨', color: '#EC4899', gradient: ['#EC4899', '#BE185D'], description: 'Habilidad para percibir el mundo visual-espacial con precisión y transformar las percepciones iniciales.', careers: ['Arquitecto/a', 'Diseñador/a gráfico', 'Piloto', 'Escultor/a', 'Cirujano/a', 'Fotógrafo/a'], famous: 'Da Vinci, Picasso, Frank Lloyd Wright', studyTips: ['Usa mapas conceptuales con colores', 'Visualiza los conceptos como imágenes', 'Aprende con diagramas y modelos 3D'] },
      MI: { label: 'Musical', emoji: '🎵', color: '#F59E0B', gradient: ['#F59E0B', '#D97706'], description: 'Sensibilidad ante el ritmo, la melodía, el timbre y la armonía.', careers: ['Músico/a', 'Compositor/a', 'Director/a de orquesta', 'Productor musical', 'Terapeuta musical'], famous: 'Mozart, Beethoven, Björk, Miles Davis', studyTips: ['Convierte listas de conceptos en canciones', 'Estudia con música instrumental de fondo', 'Usa ritmos para memorizar secuencias'] },
      KC: { label: 'Corporal-Kinestésica', emoji: '⚡', color: '#10B981', gradient: ['#10B981', '#059669'], description: 'Habilidad para usar el propio cuerpo de manera fina o gruesa para expresarse o resolver problemas.', careers: ['Deportista', 'Bailarín/a', 'Cirujano/a', 'Actor/actriz', 'Fisioterapeuta', 'Artesano/a'], famous: 'Michael Jordan, Simone Biles, Charlie Chaplin', studyTips: ['Aprende caminando o en movimiento', 'Usa objetos físicos para representar conceptos', 'Experimenta prácticas antes de teorizar'] },
      IN: { label: 'Intrapersonal', emoji: '🧘', color: '#8B5CF6', gradient: ['#8B5CF6', '#6D28D9'], description: 'Capacidad de conocerse a uno mismo profundamente, manejar las emociones propias y motivaciones.', careers: ['Psicólogo/a', 'Filósofo/a', 'Escritor/a', 'Investigador/a', 'Emprendedor/a', 'Coach personal'], famous: 'Sigmund Freud, Frida Kahlo, Nietzsche', studyTips: ['Lleva un diario de aprendizaje reflexivo', 'Estudia en soledad y a tu propio ritmo', 'Conecta cada concepto con tu experiencia personal'] },
      IE: { label: 'Interpersonal', emoji: '🤝', color: '#EF4444', gradient: ['#EF4444', '#DC2626'], description: 'Habilidad para entender las intenciones, motivaciones y deseos de los demás.', careers: ['Líder', 'Maestro/a', 'Político/a', 'Terapeuta', 'Trabajador/a social', 'Vendedor/a'], famous: 'Nelson Mandela, Oprah Winfrey, Gandhi', studyTips: ['Aprende en grupos de estudio', 'Enseña lo aprendido a otras personas', 'Participa en debates y foros'] },
      NT: { label: 'Naturalista', emoji: '🌿', color: '#84CC16', gradient: ['#84CC16', '#65A30D'], description: 'Habilidad para reconocer y categorizar objetos y patrones naturales.', careers: ['Biólogo/a', 'Ecólogo/a', 'Veterinario/a', 'Geógrafo/a', 'Chef', 'Paisajista'], famous: 'Charles Darwin, Jane Goodall, David Attenborough', studyTips: ['Aprende en contacto con la naturaleza', 'Clasifica y categoriza la información como en taxonomía', 'Relaciona conceptos con fenómenos naturales'] },
    },
  },
};
